default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bicycle_development
  username: postgres
  password: 3441

test:
  <<: *default
  database: bicycle_test
  username: postgres
  password: 3441  

